### ISSUE TITLE
README.md 작성

### ISSUE THREAD

**Issue by Icecoffee2500** [Team-W3B/Project2#26]

**Comment by Icecoffee2500** [comment]
다음과 같이 README.md 수정하였습니다.

# Assignment2

## 팀장
2016722087 임태헌 (Icecoffee2500)

## 팀원
2017202060 김도연 (kimdoyeon817)<br/>
2018202043 김경범 (KKGB)

**Comment by kimdoyeon817** [comment]
이대로 진행하겠습니다
